<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Ashok" name="com.vtg.auto.vtghometestnew.VTGHomeTest1" tests="4" failures="1" timestamp="2023-02-04T21:36:49 IST" time="23.179" errors="0">
  <testcase name="VerifyLoginTest2" time="4.795" classname="com.vtg.auto.vtghometestnew.VTGHomeTest1"/>
  <system-out/>
  <testcase name="VerifyLoginTest3" time="8.461" classname="com.vtg.auto.vtghometestnew.VTGHomeTest1"/>
  <system-out/>
  <testcase name="VerifyLoginTest1" time="5.973" classname="com.vtg.auto.vtghometestnew.VTGHomeTest1">
    <failure type="java.lang.AssertionError" message="expected [tesing] but found [Google]">
      <![CDATA[java.lang.AssertionError: expected [tesing] but found [Google]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.vtg.auto.vtghometestnew.VTGHomeTest1.VerifyLoginTest1(VTGHomeTest1.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.vtg.auto.driver.Driver.main(Driver.java:27)
]]>
    </failure>
  </testcase> <!-- VerifyLoginTest1 -->
  <system-out/>
  <testcase name="VerifyLoginTest4" time="3.950" classname="com.vtg.auto.vtghometestnew.VTGHomeTest1"/>
  <system-out/>
</testsuite> <!-- com.vtg.auto.vtghometestnew.VTGHomeTest1 -->
